// Industrial Gas Database for Flowtech AI Flow Sizing Calculator
// Properties at STP (0°C, 1 atm) unless noted otherwise
// Sources: Engineering Toolbox, RoyMech, Pipe Flow Calculations, NIST

export interface GasData {
  name: string;           // Display name
  formula: string;        // Chemical formula
  molecularWeight: number; // g/mol
  density: number;        // kg/m³ at STP (0°C, 1 atm)
  viscosity: number;      // cP (dynamic viscosity) at STP
  specificGravity: number; // SG relative to air = 1 (MW / 28.9647)
  category: string;       // Gas category
  cp: number;             // Specific heat J/(kg·K)
  gamma: number;          // Cp/Cv ratio
  rSpecific: number;      // Specific gas constant J/(kg·K)
  criticalTemp: number;   // K
  criticalPressure: number; // bar
  notes?: string;
  typicalPressure?: string; // Typical operating pressure range
}

export const GAS_CATEGORIES = [
  "Atmospheric",
  "Fuel Gas",
  "Inert Gas",
  "Process Gas",
  "Reactive Gas",
  "Refrigerant",
  "Specialty Gas",
] as const;

export const GASES_DB: GasData[] = [
  // === ATMOSPHERIC GASES ===
  {
    name: "Air",
    formula: "N₂+O₂",
    molecularWeight: 28.97,
    density: 1.293,   // at 0°C; 1.205 at 20°C
    viscosity: 0.0173,
    specificGravity: 1.0002,
    category: "Atmospheric",
    cp: 1005,
    gamma: 1.4,
    rSpecific: 287,
    criticalTemp: 132.5,
    criticalPressure: 37.7,
    notes: "Standard dry air",
    typicalPressure: "1-10 bar",
  },
  {
    name: "Compressed Air",
    formula: "N₂+O₂",
    molecularWeight: 28.97,
    density: 1.293,
    viscosity: 0.0173,
    specificGravity: 1.0002,
    category: "Atmospheric",
    cp: 1005,
    gamma: 1.4,
    rSpecific: 287,
    criticalTemp: 132.5,
    criticalPressure: 37.7,
    notes: "Compressed air for industrial use",
    typicalPressure: "6-10 bar",
  },
  {
    name: "Instrument Air",
    formula: "N₂+O₂",
    molecularWeight: 28.97,
    density: 1.293,
    viscosity: 0.0173,
    specificGravity: 1.0002,
    category: "Atmospheric",
    cp: 1005,
    gamma: 1.4,
    rSpecific: 287,
    criticalTemp: 132.5,
    criticalPressure: 37.7,
    notes: "Dry filtered air for instrumentation",
    typicalPressure: "5-7 bar",
  },
  {
    name: "Nitrogen",
    formula: "N₂",
    molecularWeight: 28.01,
    density: 1.250,
    viscosity: 0.0166,
    specificGravity: 0.967,
    category: "Inert Gas",
    cp: 1040,
    gamma: 1.4,
    rSpecific: 297,
    criticalTemp: 126.2,
    criticalPressure: 33.9,
    notes: "Most common inert purge gas",
    typicalPressure: "1-40 bar",
  },
  {
    name: "Oxygen",
    formula: "O₂",
    molecularWeight: 32.0,
    density: 1.429,
    viscosity: 0.0192,
    specificGravity: 1.1048,
    category: "Atmospheric",
    cp: 918,
    gamma: 1.4,
    rSpecific: 260,
    criticalTemp: 154.6,
    criticalPressure: 50.4,
    notes: "Oxidizer - safety precautions required",
    typicalPressure: "1-150 bar",
  },
  {
    name: "Carbon Dioxide",
    formula: "CO₂",
    molecularWeight: 44.01,
    density: 1.977,
    viscosity: 0.0137,
    specificGravity: 1.5194,
    category: "Process Gas",
    cp: 844,
    gamma: 1.3,
    rSpecific: 189,
    criticalTemp: 304.1,
    criticalPressure: 73.8,
    notes: "Sublimes at atmospheric pressure",
    typicalPressure: "1-50 bar",
  },

  // === FUEL GASES ===
  {
    name: "Natural Gas",
    formula: "CH₄+C₂H₆+...",
    molecularWeight: 19.5,
    density: 0.803,             // varies 0.7-0.92 depending on composition
    viscosity: 0.0109,
    specificGravity: 0.6732,
    category: "Fuel Gas",
    cp: 2345,
    gamma: 1.27,
    rSpecific: 426,
    criticalTemp: 190,
    criticalPressure: 46,
    notes: "Pipeline natural gas. Composition varies by source. Predominantly CH₄ (85-95%). Low wetness risk under normal conditions. Watch for heavy hydrocarbon dew point (HCDP) in transmission pipelines.",
    typicalPressure: "1-80 bar",
  },
  {
    name: "Methane",
    formula: "CH₄",
    molecularWeight: 16.043,     // NIST: 16.043 g/mol
    density: 0.717,              // at 0°C, 1 atm (STP); ~0.667 at 20°C
    viscosity: 0.0103,
    specificGravity: 0.5539,           // 10.3 μPa·s = 0.0103 cP at 20°C, 1 atm
    category: "Fuel Gas",
    cp: 2483,
    gamma: 1.32,
    rSpecific: 518.28,           // R = 518.28 J/(kg·K)
    criticalTemp: 190.551,       // -82.59°C
    criticalPressure: 45.99,     // 45.99 bar
    notes: "LOW wetness risk — condensation only at cryogenic temps. Non-corrosive. Boiling point: -161.6°C. At 10 bar: condensation at -120°C. Main component of natural gas and LNG.",
    typicalPressure: "1-200 bar",
  },
  {
    name: "Biogas",
    formula: "CH₄+CO₂",
    molecularWeight: 23.5,
    density: 1.10,    // varies 0.95-1.25 depending on CO₂%
    viscosity: 0.013,
    specificGravity: 0.8113,
    category: "Fuel Gas",
    cp: 2000,
    gamma: 1.33,
    rSpecific: 354,
    criticalTemp: 200,
    criticalPressure: 50,
    notes: "Typically 50-70% CH₄, 30-50% CO₂. Density varies.",
    typicalPressure: "1-10 bar",
  },
  {
    name: "Propane",
    formula: "C₃H₈",
    molecularWeight: 44.1,
    density: 1.882,
    viscosity: 0.0076,
    specificGravity: 1.5225,
    category: "Fuel Gas",
    cp: 1685,
    gamma: 1.15,
    rSpecific: 188,
    criticalTemp: 369.8,
    criticalPressure: 42.5,
    notes: "LPG component. Vapor at ambient conditions.",
    typicalPressure: "1-15 bar",
  },
  {
    name: "Butane",
    formula: "C₄H₁₀",
    molecularWeight: 58.12,
    density: 2.489,
    viscosity: 0.0081,
    specificGravity: 2.0066,
    category: "Fuel Gas",
    cp: 1675,
    gamma: 1.11,
    rSpecific: 143,
    criticalTemp: 425.2,
    criticalPressure: 38.0,
    notes: "LPG component. Heavier than propane.",
    typicalPressure: "1-5 bar",
  },
  {
    name: "LPG (Liquefied Petroleum Gas)",
    formula: "C₃H₈+C₄H₁₀",
    molecularWeight: 51.0,
    density: 2.15,    // vapor at STP
    viscosity: 0.0078,
    specificGravity: 1.7608,
    category: "Fuel Gas",
    cp: 1680,
    gamma: 1.13,
    rSpecific: 163,
    criticalTemp: 397,
    criticalPressure: 40,
    notes: "Mixture of propane and butane. Density varies with mix ratio.",
    typicalPressure: "1-15 bar",
  },
  {
    name: "LNG (Liquefied Natural Gas)",
    formula: "CH₄",
    molecularWeight: 16.043,    // NIST: 16.043 g/mol
    density: 0.717,             // vapor at 0°C, 1 atm
    viscosity: 0.0103,
    specificGravity: 0.5539,          // 10.3 μPa·s at 20°C
    category: "Fuel Gas",
    cp: 2483,
    gamma: 1.32,
    rSpecific: 518.28,          // R = 518.28 J/(kg·K)
    criticalTemp: 190.551,      // -82.59°C
    criticalPressure: 45.99,    // 45.99 bar
    notes: "LOW wetness risk. Regasified LNG — primarily methane. Non-corrosive. Cryogenic liquid density: 420-470 kg/m³ at -162°C. Vaporization temp: -161.6°C at 1 atm.",
    typicalPressure: "1-80 bar",
  },
  {
    name: "Acetylene",
    formula: "C₂H₂",
    molecularWeight: 26.04,
    density: 1.170,
    viscosity: 0.0094,
    specificGravity: 0.899,
    category: "Fuel Gas",
    cp: 1683,
    gamma: 1.25,
    rSpecific: 319,
    criticalTemp: 308.4,
    criticalPressure: 61.4,
    notes: "Highly flammable. Used in welding/cutting.",
    typicalPressure: "1-15 bar",
  },
  {
    name: "Ethane",
    formula: "C₂H₆",
    molecularWeight: 30.07,
    density: 1.264,
    viscosity: 0.0094,
    specificGravity: 1.0382,
    category: "Fuel Gas",
    cp: 1729,
    gamma: 1.2,
    rSpecific: 277,
    criticalTemp: 305.3,
    criticalPressure: 48.8,
    notes: "Natural gas component, petrochemical feedstock",
    typicalPressure: "1-50 bar",
  },
  {
    name: "Ethylene",
    formula: "C₂H₄",
    molecularWeight: 28.05,
    density: 1.174,
    viscosity: 0.0094,
    specificGravity: 0.9684,
    category: "Fuel Gas",
    cp: 1528,
    gamma: 1.25,
    rSpecific: 297,
    criticalTemp: 282.3,
    criticalPressure: 50.4,
    notes: "Petrochemical feedstock. Unsaturated hydrocarbon.",
    typicalPressure: "1-80 bar",
  },
  {
    name: "Hydrogen",
    formula: "H₂",
    molecularWeight: 2.016,
    density: 0.0899,
    viscosity: 0.0084,
    specificGravity: 0.0696,
    category: "Fuel Gas",
    cp: 14266,
    gamma: 1.41,
    rSpecific: 4124,
    criticalTemp: 33.2,
    criticalPressure: 13.0,
    notes: "Lightest gas. Highly flammable. Very low density.",
    typicalPressure: "1-700 bar",
  },
  {
    name: "Town Gas / Producer Gas",
    formula: "CO+H₂+CH₄",
    molecularWeight: 18.0,
    density: 0.65,
    viscosity: 0.014,
    specificGravity: 0.6214,
    category: "Fuel Gas",
    cp: 2200,
    gamma: 1.38,
    rSpecific: 462,
    criticalTemp: 140,
    criticalPressure: 35,
    notes: "Man-made fuel gas from coal gasification",
    typicalPressure: "0.1-1 bar",
  },
  {
    name: "Coke Oven Gas",
    formula: "H₂+CH₄+CO",
    molecularWeight: 11.0,
    density: 0.45,
    viscosity: 0.012,
    specificGravity: 0.3798,
    category: "Fuel Gas",
    cp: 2800,
    gamma: 1.38,
    rSpecific: 755,
    criticalTemp: 100,
    criticalPressure: 30,
    notes: "By-product of coke production. High H₂ content.",
    typicalPressure: "0.1-1 bar",
  },
  {
    name: "Blast Furnace Gas",
    formula: "N₂+CO+CO₂",
    molecularWeight: 30.0,
    density: 1.25,
    viscosity: 0.018,
    specificGravity: 1.0357,
    category: "Fuel Gas",
    cp: 1200,
    gamma: 1.4,
    rSpecific: 277,
    criticalTemp: 140,
    criticalPressure: 40,
    notes: "Steel plant waste gas. Low calorific value.",
    typicalPressure: "0.1-1 bar",
  },

  // === INERT GASES ===
  {
    name: "Helium",
    formula: "He",
    molecularWeight: 4.003,
    density: 0.178,
    viscosity: 0.0199,
    specificGravity: 0.1382,
    category: "Specialty Gas",
    cp: 5193,
    gamma: 1.66,
    rSpecific: 2079,
    criticalTemp: 5.2,
    criticalPressure: 2.3,
    notes: "Very light inert gas. Used in leak detection, cryogenics.",
    typicalPressure: "1-200 bar",
  },
  {
    name: "Argon",
    formula: "Ar",
    molecularWeight: 39.95,
    density: 1.784,
    viscosity: 0.0209,
    specificGravity: 1.3793,
    category: "Inert Gas",
    cp: 520,
    gamma: 1.67,
    rSpecific: 208,
    criticalTemp: 150.9,
    criticalPressure: 49.0,
    notes: "Shielding gas for welding. Inert atmosphere.",
    typicalPressure: "1-200 bar",
  },
  {
    name: "Neon",
    formula: "Ne",
    molecularWeight: 20.18,
    density: 0.900,
    viscosity: 0.0297,
    specificGravity: 0.6967,
    category: "Specialty Gas",
    cp: 1030,
    gamma: 1.64,
    rSpecific: 412,
    criticalTemp: 44.4,
    criticalPressure: 27.6,
    notes: "Noble gas. Used in lighting, cryogenics.",
    typicalPressure: "1-100 bar",
  },
  {
    name: "Krypton",
    formula: "Kr",
    molecularWeight: 83.8,
    density: 3.708,
    viscosity: 0.0232,
    specificGravity: 2.8932,
    category: "Specialty Gas",
    cp: 248,
    gamma: 1.68,
    rSpecific: 99,
    criticalTemp: 209.4,
    criticalPressure: 55.0,
    notes: "Rare noble gas. Insulation applications.",
    typicalPressure: "1-50 bar",
  },

  // === PROCESS GASES ===
  {
    name: "Carbon Monoxide",
    formula: "CO",
    molecularWeight: 28.01,
    density: 1.250,
    viscosity: 0.0166,
    specificGravity: 0.967,
    category: "Process Gas",
    cp: 1040,
    gamma: 1.4,
    rSpecific: 297,
    criticalTemp: 133.0,
    criticalPressure: 35.0,
    notes: "Toxic! Syngas component. Colorless, odorless.",
    typicalPressure: "1-50 bar",
  },
  {
    name: "Ammonia",
    formula: "NH₃",
    molecularWeight: 17.031,     // NIST: 17.0305 g/mol
    density: 0.772,              // at 0°C, 1 atm (STP); 0.717 at 20°C
    viscosity: 0.00918,
    specificGravity: 0.588,          // 9.18 μPa·s = 0.00918 cP at 20°C, 1 atm
    category: "Process Gas",
    cp: 2200,
    gamma: 1.31,                 // isentropic exponent γ = 1.31
    rSpecific: 488.218,          // R = 488.2175 J/(kg·K)
    criticalTemp: 405.4,         // 132.25°C
    criticalPressure: 113.39,    // 113.39 bar
    notes: "HIGH WETNESS RISK. Toxic, corrosive to Cu alloys (stress corrosion cracking). At 5 bar: condensation at +4°C. At 10 bar: +25°C. At 20 bar: +51°C. Carbon steel OK for anhydrous NH₃. NEVER use copper, brass, bronze.",
    typicalPressure: "1-30 bar",
  },
  {
    name: "Chlorine",
    formula: "Cl₂",
    molecularWeight: 70.906,    // NIST/IUPAC: 70.906 g/mol
    density: 3.214,             // at 0°C, 1 atm (STP); 2.994 at 20°C
    viscosity: 0.0129,
    specificGravity: 2.448,          // 12.9 μPa·s = 0.0129 cP at 20°C, 1 atm
    category: "Process Gas",
    cp: 478,
    gamma: 1.355,
    rSpecific: 117.259,         // R = 117.259 J/(kg·K)
    criticalTemp: 416.96,       // 143.8°C
    criticalPressure: 79.914,   // 79.914 bar
    notes: "HIGH WETNESS RISK. Toxic and corrosive. At 5 bar: condensation at -12°C. At 10 bar: +5°C. At 20 bar: +28°C. Wet Cl₂ forms HCl + HOCl — attacks all metals except Ti, Hastelloy C, PTFE, PVDF. Must be dried to dew point -40°C.",
    typicalPressure: "1-20 bar",
  },
  {
    name: "Sulfur Dioxide",
    formula: "SO₂",
    molecularWeight: 64.06,
    density: 2.279,
    viscosity: 0.0118,
    specificGravity: 2.2117,
    category: "Process Gas",
    cp: 622,
    gamma: 1.29,
    rSpecific: 130,
    criticalTemp: 430.8,
    criticalPressure: 78.8,
    notes: "Toxic. Used in refrigeration, chemical processes.",
    typicalPressure: "1-10 bar",
  },
  {
    name: "Hydrogen Sulfide",
    formula: "H₂S",
    molecularWeight: 34.08,
    density: 1.434,
    viscosity: 0.0117,
    specificGravity: 1.1766,
    category: "Process Gas",
    cp: 1024,
    gamma: 1.32,
    rSpecific: 244,
    criticalTemp: 373.6,
    criticalPressure: 89.6,
    notes: "Highly toxic! Rotten egg smell. Sour gas processing.",
    typicalPressure: "1-100 bar",
  },
  {
    name: "Hydrogen Chloride",
    formula: "HCl",
    molecularWeight: 36.46,
    density: 1.528,
    viscosity: 0.0134,
    specificGravity: 1.2588,
    category: "Process Gas",
    cp: 800,
    gamma: 1.41,
    rSpecific: 228,
    criticalTemp: 324.6,
    criticalPressure: 83.1,
    notes: "Corrosive. Forms hydrochloric acid in water.",
    typicalPressure: "1-20 bar",
  },
  {
    name: "Nitrous Oxide",
    formula: "N₂O",
    molecularWeight: 44.01,
    density: 1.843,
    viscosity: 0.0135,
    specificGravity: 1.5194,
    category: "Process Gas",
    cp: 880,
    gamma: 1.31,
    rSpecific: 189,
    criticalTemp: 309.6,
    criticalPressure: 72.4,
    notes: "Laughing gas. Oxidizer, medical applications.",
    typicalPressure: "1-50 bar",
  },
  {
    name: "Nitric Oxide",
    formula: "NO",
    molecularWeight: 30.01,
    density: 1.249,
    viscosity: 0.0178,
    specificGravity: 1.0361,
    category: "Process Gas",
    cp: 993,
    gamma: 1.39,
    rSpecific: 277,
    criticalTemp: 180.2,
    criticalPressure: 64.8,
    notes: "Reactive gas. Reacts with O₂ to form NO₂.",
    typicalPressure: "1-10 bar",
  },

  // === REFRIGERANT GASES ===
  {
    name: "R-134a",
    formula: "CF₃CH₂F",
    molecularWeight: 102.03,
    density: 4.25,
    viscosity: 0.011,
    specificGravity: 3.5226,
    category: "Refrigerant",
    cp: 1430,
    gamma: 1.11,
    rSpecific: 81.5,
    criticalTemp: 374.2,
    criticalPressure: 40.6,
    notes: "Common refrigerant. HFC replacement for R-12.",
    typicalPressure: "1-30 bar",
  },
  {
    name: "R-22",
    formula: "CHClF₂",
    molecularWeight: 86.47,
    density: 3.86,
    viscosity: 0.012,
    specificGravity: 2.9854,
    category: "Refrigerant",
    cp: 1200,
    gamma: 1.18,
    rSpecific: 96.1,
    criticalTemp: 369.3,
    criticalPressure: 49.9,
    notes: "HCFC refrigerant. Being phased out.",
    typicalPressure: "1-30 bar",
  },
  {
    name: "R-404A",
    formula: "R125/R143a/R134a",
    molecularWeight: 97.6,
    density: 4.50,
    viscosity: 0.012,
    specificGravity: 3.3696,
    category: "Refrigerant",
    cp: 1300,
    gamma: 1.12,
    rSpecific: 85.1,
    criticalTemp: 345,
    criticalPressure: 37.4,
    notes: "Blend refrigerant for commercial refrigeration.",
    typicalPressure: "1-30 bar",
  },
  {
    name: "R-410A",
    formula: "R32/R125",
    molecularWeight: 72.6,
    density: 2.97,
    viscosity: 0.013,
    specificGravity: 2.5065,
    category: "Refrigerant",
    cp: 1650,
    gamma: 1.13,
    rSpecific: 114.5,
    criticalTemp: 344.5,
    criticalPressure: 49.0,
    notes: "Blend refrigerant for air conditioning.",
    typicalPressure: "1-40 bar",
  },

  // === SPECIALTY / INDUSTRIAL GASES ===
  {
    name: "Boron Trifluoride",
    formula: "BF₃",
    molecularWeight: 67.8,
    density: 2.99,
    viscosity: 0.017,
    specificGravity: 2.3408,
    category: "Specialty Gas",
    cp: 700,
    gamma: 1.2,
    rSpecific: 123,
    criticalTemp: 340,
    criticalPressure: 50,
    notes: "Used in semiconductor manufacturing.",
    typicalPressure: "1-10 bar",
  },
  {
    name: "Synthesis Gas (Syngas)",
    formula: "CO+H₂",
    molecularWeight: 15.0,
    density: 0.55,
    viscosity: 0.010,
    specificGravity: 0.5179,
    category: "Process Gas",
    cp: 2800,
    gamma: 1.4,
    rSpecific: 555,
    criticalTemp: 100,
    criticalPressure: 35,
    notes: "H₂:CO ratio varies (1:1 to 3:1). Feedstock for chemicals.",
    typicalPressure: "10-80 bar",
  },
  {
    name: "Flue Gas",
    formula: "N₂+CO₂+H₂O+O₂",
    molecularWeight: 30.0,
    density: 1.30,
    viscosity: 0.020,
    specificGravity: 1.0357,
    category: "Process Gas",
    cp: 1100,
    gamma: 1.38,
    rSpecific: 277,
    criticalTemp: 150,
    criticalPressure: 40,
    notes: "Combustion exhaust. Composition varies with fuel.",
    typicalPressure: "0.1-1 bar (atmospheric)",
  },
  {
    name: "Digester Gas / Sewage Gas",
    formula: "CH₄+CO₂",
    molecularWeight: 24.0,
    density: 1.05,
    viscosity: 0.012,
    specificGravity: 0.8286,
    category: "Fuel Gas",
    cp: 1900,
    gamma: 1.33,
    rSpecific: 346,
    criticalTemp: 195,
    criticalPressure: 48,
    notes: "Anaerobic digestion product. 60-70% CH₄.",
    typicalPressure: "0.1-1 bar",
  },
  {
    name: "Ethyl Chloride",
    formula: "C₂H₅Cl",
    molecularWeight: 64.51,
    density: 2.88,
    viscosity: 0.0094,
    specificGravity: 2.2272,
    category: "Process Gas",
    cp: 1340,
    gamma: 1.13,
    rSpecific: 129,
    criticalTemp: 460,
    criticalPressure: 52.7,
    notes: "Refrigerant and chemical intermediate.",
    typicalPressure: "1-10 bar",
  },
  {
    name: "Methyl Chloride",
    formula: "CH₃Cl",
    molecularWeight: 50.49,
    density: 2.15,
    viscosity: 0.010,
    specificGravity: 1.7432,
    category: "Process Gas",
    cp: 1005,
    gamma: 1.2,
    rSpecific: 165,
    criticalTemp: 416.3,
    criticalPressure: 66.8,
    notes: "Refrigerant and chemical intermediate.",
    typicalPressure: "1-10 bar",
  },
  {
    name: "Phosgene",
    formula: "COCl₂",
    molecularWeight: 98.92,
    density: 3.42,
    viscosity: 0.012,
    specificGravity: 3.4152,
    category: "Process Gas",
    cp: 580,
    gamma: 1.17,
    rSpecific: 84,
    criticalTemp: 455,
    criticalPressure: 56.7,
    notes: "Extremely toxic! Chemical warfare agent precursor.",
    typicalPressure: "1-5 bar",
  },
  {
    name: "Silane",
    formula: "SiH₄",
    molecularWeight: 32.12,
    density: 1.44,
    viscosity: 0.010,
    specificGravity: 1.1089,
    category: "Specialty Gas",
    cp: 1340,
    gamma: 1.27,
    rSpecific: 259,
    criticalTemp: 270,
    criticalPressure: 48.4,
    notes: "Pyrophoric! Semiconductor manufacturing.",
    typicalPressure: "1-50 bar",
  },
  {
    name: "Sulfur Hexafluoride",
    formula: "SF₆",
    molecularWeight: 146.06,
    density: 6.16,
    viscosity: 0.0155,
    specificGravity: 5.0427,
    category: "Specialty Gas",
    cp: 665,
    gamma: 1.09,
    rSpecific: 56.9,
    criticalTemp: 318.7,
    criticalPressure: 37.6,
    notes: "Electrical insulation gas. Very high density.",
    typicalPressure: "1-10 bar",
  },

  // === EXPANDED: NOBLE GASES ===
  {
    name: "Xenon",
    formula: "Xe",
    molecularWeight: 131.29,
    density: 5.86,
    viscosity: 0.0226,
    specificGravity: 4.5328,
    category: "Specialty Gas",
    cp: 158,
    gamma: 1.67,
    rSpecific: 63.3,
    criticalTemp: 289.7,
    criticalPressure: 57.6,
    notes: "Very heavy inert gas. Medical anesthesia, satellite ion propulsion, lighting.",
    typicalPressure: "1-50 bar",
  },
  {
    name: "Radon",
    formula: "Rn",
    molecularWeight: 222.02,
    density: 9.91,
    viscosity: 0.0229,
    specificGravity: 7.6652,
    category: "Specialty Gas",
    cp: 94,
    gamma: 1.62,
    rSpecific: 37.5,
    criticalTemp: 377.4,
    criticalPressure: 63.2,
    notes: "Radioactive noble gas. No industrial use due to radioactivity.",
    typicalPressure: "N/A",
  },

  // === EXPANDED: HALOGEN GASES ===
  {
    name: "Fluorine",
    formula: "F₂",
    molecularWeight: 38.0,
    density: 1.696,
    viscosity: 0.0247,
    specificGravity: 1.3119,
    category: "Process Gas",
    cp: 825,
    gamma: 1.36,
    rSpecific: 219,
    criticalTemp: 144.3,
    criticalPressure: 52.2,
    notes: "EXTREMELY reactive! Strongest oxidizer known. Handle with extreme care.",
    typicalPressure: "1-10 bar",
  },
  {
    name: "Boron Trifluoride",
    formula: "BF₃",
    molecularWeight: 67.8,
    density: 2.99,
    viscosity: 0.017,
    specificGravity: 2.3408,
    category: "Process Gas",
    cp: 700,
    gamma: 1.2,
    rSpecific: 123,
    criticalTemp: 340,
    criticalPressure: 50,
    notes: "Used in semiconductor manufacturing.",
    typicalPressure: "1-10 bar",
  },
  {
    name: "Germane",
    formula: "GeH₄",
    molecularWeight: 76.62,
    density: 3.42,
    viscosity: 0.013,
    specificGravity: 2.6453,
    category: "Specialty Gas",
    cp: 312,
    gamma: 1.27,
    rSpecific: 109,
    criticalTemp: 308.1,
    criticalPressure: 55.2,
    notes: "Toxic, pyrophoric! Semiconductor CVD processes.",
    typicalPressure: "1-20 bar",
  },
  {
    name: "Dichlorosilane",
    formula: "SiH₂Cl₂",
    molecularWeight: 101.01,
    density: 4.51,
    viscosity: 0.011,
    specificGravity: 3.4873,
    category: "Process Gas",
    cp: 250,
    gamma: 1.18,
    rSpecific: 82.3,
    criticalTemp: 330,
    criticalPressure: 47.6,
    notes: "Pyrophoric! CVD precursor for silicon deposition.",
    typicalPressure: "1-10 bar",
  },
  {
    name: "Tungsten Hexafluoride",
    formula: "WF₆",
    molecularWeight: 297.84,
    density: 13.29,
    viscosity: 0.018,
    specificGravity: 10.2829,
    category: "Specialty Gas",
    cp: 120,
    gamma: 1.08,
    rSpecific: 27.9,
    criticalTemp: 439.1,
    criticalPressure: 43.1,
    notes: "EXTREMELY dense. CVD for tungsten films.",
    typicalPressure: "1-5 bar",
  },

  // === EXPANDED: CFC / REFRIGERANT GASES ===
  {
    name: "R-11 (CFC-11)",
    formula: "CCl₃F",
    molecularWeight: 137.37,
    density: 5.72,
    viscosity: 0.012,
    specificGravity: 4.7427,
    category: "Refrigerant",
    cp: 680,
    gamma: 1.14,
    rSpecific: 60.5,
    criticalTemp: 471.2,
    criticalPressure: 44.1,
    notes: "Being phased out (Montreal Protocol). Ozone depleting.",
    typicalPressure: "1-10 bar",
  },
  {
    name: "R-12 (CFC-12)",
    formula: "CCl₂F₂",
    molecularWeight: 120.91,
    density: 5.02,
    viscosity: 0.012,
    specificGravity: 4.1744,
    category: "Refrigerant",
    cp: 680,
    gamma: 1.14,
    rSpecific: 68.7,
    criticalTemp: 385.1,
    criticalPressure: 41.6,
    notes: "Being phased out. Formerly used in automotive AC.",
    typicalPressure: "1-20 bar",
  },
  {
    name: "R-123",
    formula: "CHCl₂CF₃",
    molecularWeight: 152.93,
    density: 6.47,
    viscosity: 0.011,
    specificGravity: 5.2799,
    category: "Refrigerant",
    cp: 650,
    gamma: 1.12,
    rSpecific: 54.3,
    criticalTemp: 456.9,
    criticalPressure: 36.7,
    notes: "HCFC replacement for R-11. Being phased out.",
    typicalPressure: "1-10 bar",
  },

  // === EXPANDED: CALIBRATION & MIXTURE GASES ===
  {
    name: "Zero Air",
    formula: "N₂+O₂",
    molecularWeight: 28.97,
    density: 1.293,
    viscosity: 0.0173,
    specificGravity: 1.0002,
    category: "Specialty Gas",
    cp: 1005,
    gamma: 1.4,
    rSpecific: 287,
    criticalTemp: 132.5,
    criticalPressure: 37.7,
    notes: "Hydrocarbon-free air. Used for gas analyzer calibration.",
    typicalPressure: "1-50 bar",
  },
  {
    name: "Helium-Neon Mixture",
    formula: "He+Ne",
    molecularWeight: 8.0,
    density: 0.45,
    viscosity: 0.018,
    specificGravity: 0.2762,
    category: "Specialty Gas",
    cp: 3500,
    gamma: 1.55,
    rSpecific: 1040,
    criticalTemp: 30,
    criticalPressure: 10,
    notes: "Laser gas mixture (HeNe laser).",
    typicalPressure: "1-20 bar",
  },

  // === EXPANDED: PROCESS / INDUSTRIAL GASES ===
  {
    name: "Chlorine Dioxide",
    formula: "ClO₂",
    molecularWeight: 67.45,
    density: 2.98,
    viscosity: 0.013,
    specificGravity: 2.3287,
    category: "Process Gas",
    cp: 360,
    gamma: 1.33,
    rSpecific: 123,
    criticalTemp: 432.0,
    criticalPressure: 78.8,
    notes: "Toxic, explosive! Water treatment bleaching agent.",
    typicalPressure: "0.1-1 bar",
  },
  {
    name: "Ozone",
    formula: "O₃",
    molecularWeight: 48.0,
    density: 2.14,
    viscosity: 0.0128,
    specificGravity: 1.6572,
    category: "Process Gas",
    cp: 820,
    gamma: 1.29,
    rSpecific: 173,
    criticalTemp: 261.1,
    criticalPressure: 55.0,
    notes: "Toxic, unstable. Water treatment, bleaching.",
    typicalPressure: "0.1-1 bar",
  },
  {
    name: "Diborane",
    formula: "B₂H₆",
    molecularWeight: 27.67,
    density: 1.23,
    viscosity: 0.008,
    specificGravity: 0.9553,
    category: "Specialty Gas",
    cp: 1800,
    gamma: 1.18,
    rSpecific: 301,
    criticalTemp: 289.8,
    criticalPressure: 40.5,
    notes: "EXTREMELY toxic, pyrophoric! Semiconductor doping.",
    typicalPressure: "1-10 bar",
  },
  {
    name: "Methyl Bromide",
    formula: "CH₃Br",
    molecularWeight: 94.94,
    density: 4.24,
    viscosity: 0.011,
    specificGravity: 3.2778,
    category: "Process Gas",
    cp: 450,
    gamma: 1.22,
    rSpecific: 87.6,
    criticalTemp: 467.2,
    criticalPressure: 85.0,
    notes: "Toxic! Fumigant. Being phased out.",
    typicalPressure: "1-5 bar",
  },

  // === EXPANDED: NATURAL GAS VARIANTS ===
  {
    name: "Liquefied Petroleum Gas (LPG)",
    formula: "C₃H₈+C₄H₁₀",
    molecularWeight: 51.0,
    density: 2.15,
    viscosity: 0.0078,
    specificGravity: 1.7608,
    category: "Fuel Gas",
    cp: 1680,
    gamma: 1.13,
    rSpecific: 163,
    criticalTemp: 397,
    criticalPressure: 40,
    notes: "Propane/butane mixture. Common domestic fuel.",
    typicalPressure: "1-15 bar",
  },
  {
    name: "Refinery Gas",
    formula: "C₁-C₄ mix",
    molecularWeight: 25.0,
    density: 1.05,
    viscosity: 0.009,
    specificGravity: 0.8631,
    category: "Fuel Gas",
    cp: 2200,
    gamma: 1.28,
    rSpecific: 333,
    criticalTemp: 200,
    criticalPressure: 45,
    notes: "Petroleum refinery off-gas. Variable composition.",
    typicalPressure: "1-20 bar",
  },
  {
    name: "Landfill Gas",
    formula: "CH₄+CO₂",
    molecularWeight: 26.0,
    density: 1.10,
    viscosity: 0.012,
    specificGravity: 0.8976,
    category: "Fuel Gas",
    cp: 2000,
    gamma: 1.32,
    rSpecific: 320,
    criticalTemp: 195,
    criticalPressure: 48,
    notes: "40-60% CH₄, remainder CO₂. Renewable energy source.",
    typicalPressure: "0.1-1 bar",
  },
];

// Search gases by name, formula, or category
export function searchGases(query: string): GasData[] {
  if (!query || query.length < 1) return [];
  const q = query.toLowerCase();
  return GASES_DB.filter(
    (g) =>
      g.name.toLowerCase().includes(q) ||
      g.formula.toLowerCase().includes(q) ||
      g.category.toLowerCase().includes(q)
  ).slice(0, 10);
}

// Calculate gas density at given pressure and temperature
// Using ideal gas law: ρ = (P * M) / (R * T)
// Where P in Pa, M in kg/mol, R = 8.314 J/(mol·K), T in K
export function calculateGasDensity(
  gas: GasData,
  pressureBarG: number,
  tempC: number
): number {
  const pAbs = (pressureBarG + 1.01325) * 100000; // Pa
  const tK = tempC + 273.15;
  const mKgMol = gas.molecularWeight / 1000; // kg/mol
  const rho = (pAbs * mKgMol) / (8.314 * tK);
  return parseFloat(rho.toFixed(4));
}

// Sutherland formula for gas viscosity vs temperature
// μ = μ_ref * (T/T_ref)^(3/2) * (T_ref + S) / (T + S)
// where S is Sutherland's constant
export function calculateGasViscosity(
  gas: GasData,
  tempC: number
): number {
  const tRef = 273.15; // 0°C reference
  const tK = tempC + 273.15;
  const muRef = gas.viscosity * 0.001; // Convert cP to Pa·s for formula

  // Sutherland constants (approximate)
  const sutherlandConstants: Record<string, number> = {
    Air: 110.4,
    Nitrogen: 111,
    Oxygen: 127,
    "Carbon Dioxide": 222,
    Hydrogen: 71.7,
    Helium: 79.4,
    Argon: 144,
    Methane: 169.7,
    Propane: 377,
    Butane: 377,
    "Natural Gas": 169,
    Ammonia: 503,
    "Carbon Monoxide": 118,
    Ethane: 252,
    Ethylene: 225,
    Acetylene: 198,
    Chlorine: 331,
    "Sulfur Dioxide": 416,
    "Hydrogen Sulfide": 331,
  };

  const s = sutherlandConstants[gas.name] ?? 110; // Default to air
  const mu =
    muRef *
    Math.pow(tK / tRef, 1.5) *
    ((tRef + s) / (tK + s));

  return parseFloat((mu * 1000).toFixed(4)); // Convert back to cP
}
