// Flowtech Liquid Viscosity Master Database - 220+ liquids across 12 categories
export interface LiquidData {
  name: string;
  category: string;
  density: number;     // kg/m³ at 20°C
  viscosity: number;   // cP at 20°C
  specificGravity: number;  // SG relative to water at 4°C (density/1000)
  conductivity?: boolean;  // true = conductive (for EM suitability)
  nonNewtonian?: boolean;  // true = non-Newtonian fluid
  concentration?: boolean; // true = concentration-dependent properties
  formula?: string;
  notes?: string;
}

export const LIQUID_CATEGORIES = [
  "Water",
  "Acid",
  "Alkali",
  "Solvent",
  "Oil",
  "Fuel",
  "Chemical",
  "Food & Beverage",
  "Pharmaceutical",
  "Slurry",
  "Gas (Liquid state)",
  "Cryogenic",
] as const;

export const LIQUIDS_DB: LiquidData[] = [
  // === WATER (13) ===
  { name: "Water", category: "Water", density: 998, viscosity: 1.0, conductivity: true,
    specificGravity: 0.998, formula: "H₂O" },
  { name: "Sea Water", category: "Water", density: 1025, viscosity: 1.08,
    specificGravity: 1.025, conductivity: true },
  { name: "Brackish Water", category: "Water", density: 1010, viscosity: 1.05,
    specificGravity: 1.01, conductivity: true },
  { name: "Demineralized Water", category: "Water", density: 998, viscosity: 1.0, conductivity: false,
    specificGravity: 0.998, notes: "Very low conductivity" },
  { name: "Distilled Water", category: "Water", density: 998, viscosity: 1.0, conductivity: false,
    specificGravity: 0.998, notes: "Very low conductivity" },
  { name: "Deionized Water", category: "Water", density: 998, viscosity: 1.0, conductivity: false,
    specificGravity: 0.998, notes: "Very low conductivity" },
  { name: "Boiler Feed Water", category: "Water", density: 980, viscosity: 0.45, conductivity: true,
    specificGravity: 0.98, notes: "At 90°C" },
  { name: "Condensate", category: "Water", density: 960, viscosity: 0.30, conductivity: true,
    specificGravity: 0.96, notes: "At 90°C" },
  { name: "Hot Water (80°C)", category: "Water", density: 972, viscosity: 0.35, conductivity: true,
    specificGravity: 0.972, notes: "At 80°C" },
  { name: "Chilled Water (5°C)", category: "Water", density: 1000, viscosity: 1.52,
    specificGravity: 1.0, conductivity: true },
  { name: "Waste Water", category: "Water", density: 1000, viscosity: 1.2,
    specificGravity: 1.0, conductivity: true },
  { name: "Raw Water", category: "Water", density: 1000, viscosity: 1.1,
    specificGravity: 1.0, conductivity: true },
  { name: "Process Water", category: "Water", density: 998, viscosity: 1.0,
    specificGravity: 0.998, conductivity: true },
  // === ACIDS (18) ===
  { name: "Hydrochloric Acid (30%)", category: "Acid", density: 1149, viscosity: 1.8, conductivity: true,
    specificGravity: 1.149, concentration: true, formula: "HCl" },
  { name: "Hydrochloric Acid (20%)", category: "Acid", density: 1098, viscosity: 1.5, conductivity: true,
    specificGravity: 1.098, concentration: true, formula: "HCl" },
  { name: "Sulfuric Acid (98%)", category: "Acid", density: 1834, viscosity: 24.0, conductivity: true,
    specificGravity: 1.834, concentration: true, formula: "H₂SO₄" },
  { name: "Sulfuric Acid (50%)", category: "Acid", density: 1398, viscosity: 4.5, conductivity: true,
    specificGravity: 1.398, concentration: true, formula: "H₂SO₄" },
  { name: "Sulfuric Acid (20%)", category: "Acid", density: 1139, viscosity: 1.5, conductivity: true,
    specificGravity: 1.139, concentration: true, formula: "H₂SO₄" },
  { name: "Nitric Acid (60%)", category: "Acid", density: 1367, viscosity: 1.2, conductivity: true,
    specificGravity: 1.367, concentration: true, formula: "HNO₃" },
  { name: "Nitric Acid (30%)", category: "Acid", density: 1180, viscosity: 1.1, conductivity: true,
    specificGravity: 1.18, concentration: true, formula: "HNO₃" },
  { name: "Phosphoric Acid (85%)", category: "Acid", density: 1685, viscosity: 75.0, conductivity: true,
    specificGravity: 1.685, concentration: true, formula: "H₃PO₄" },
  { name: "Phosphoric Acid (50%)", category: "Acid", density: 1330, viscosity: 6.0, conductivity: true,
    specificGravity: 1.33, concentration: true, formula: "H₃PO₄" },
  { name: "Acetic Acid (100%)", category: "Acid", density: 1049, viscosity: 1.22, conductivity: false,
    specificGravity: 1.049, concentration: true, formula: "CH₃COOH" },
  { name: "Acetic Acid (50%)", category: "Acid", density: 1058, viscosity: 1.8, conductivity: true,
    specificGravity: 1.058, concentration: true, formula: "CH₃COOH" },
  { name: "Citric Acid (50%)", category: "Acid", density: 1230, viscosity: 3.5, conductivity: true,
    specificGravity: 1.23, concentration: true, formula: "C₆H₈O₇" },
  { name: "Formic Acid (85%)", category: "Acid", density: 1214, viscosity: 1.8, conductivity: true,
    specificGravity: 1.214, concentration: true, formula: "HCOOH" },
  { name: "Hydrofluoric Acid (40%)", category: "Acid", density: 1130, viscosity: 1.0, conductivity: true,
    specificGravity: 1.13, concentration: true, formula: "HF" },
  { name: "Chromic Acid", category: "Acid", density: 1710, viscosity: 2.3, conductivity: true,
    specificGravity: 1.71, formula: "H₂CrO₄" },
  { name: "Battery Acid", category: "Acid", density: 1280, viscosity: 3.5, conductivity: true,
    specificGravity: 1.28, notes: "~37% H₂SO₄" },
  { name: "Aqua Regia", category: "Acid", density: 1210, viscosity: 1.1, conductivity: true,
    specificGravity: 1.21, notes: "HNO₃+HCl mixture" },
  { name: "Pickling Acid", category: "Acid", density: 1150, viscosity: 2.0, conductivity: true,
    specificGravity: 1.15, notes: "HCl based" },

  // === ALKALIS (8) ===
  { name: "Caustic Soda (50%)", category: "Alkali", density: 1525, viscosity: 75.0, conductivity: true,
    specificGravity: 1.525, concentration: true, formula: "NaOH" },
  { name: "Caustic Soda (30%)", category: "Alkali", density: 1330, viscosity: 12.0, conductivity: true,
    specificGravity: 1.33, concentration: true, formula: "NaOH" },
  { name: "Caustic Soda (20%)", category: "Alkali", density: 1220, viscosity: 4.5, conductivity: true,
    specificGravity: 1.22, concentration: true, formula: "NaOH" },
  { name: "Caustic Potash (45%)", category: "Alkali", density: 1450, viscosity: 35.0, conductivity: true,
    specificGravity: 1.45, concentration: true, formula: "KOH" },
  { name: "Caustic Potash (20%)", category: "Alkali", density: 1180, viscosity: 5.0, conductivity: true,
    specificGravity: 1.18, concentration: true, formula: "KOH" },
  { name: "Ammonia Solution (25%)", category: "Alkali", density: 910, viscosity: 0.95, conductivity: true,
    specificGravity: 0.91, concentration: true, formula: "NH₄OH" },
  { name: "Soda Ash Solution (20%)", category: "Alkali", density: 1200, viscosity: 2.5, conductivity: true,
    specificGravity: 1.2, concentration: true, formula: "Na₂CO₃" },
  { name: "Lime Water (Saturated)", category: "Alkali", density: 1050, viscosity: 2.0, conductivity: true,
    specificGravity: 1.05, formula: "Ca(OH)₂" },

  // === SOLVENTS (15) ===
  { name: "Acetone", category: "Solvent", density: 791, viscosity: 0.32, conductivity: false,
    specificGravity: 0.791, formula: "C₃H₆O" },
  { name: "Methanol", category: "Solvent", density: 792, viscosity: 0.59, conductivity: false,
    specificGravity: 0.792, formula: "CH₃OH" },
  { name: "Ethanol", category: "Solvent", density: 789, viscosity: 1.2, conductivity: false,
    specificGravity: 0.789, formula: "C₂H₅OH" },
  { name: "Isopropyl Alcohol (IPA)", category: "Solvent", density: 786, viscosity: 2.4, conductivity: false,
    specificGravity: 0.786, formula: "C₃H₈O" },
  { name: "Butanol", category: "Solvent", density: 810, viscosity: 2.95, conductivity: false,
    specificGravity: 0.81, formula: "C₄H₁₀O" },
  { name: "Ethylene Glycol", category: "Solvent", density: 1113, viscosity: 19.9, conductivity: false,
    specificGravity: 1.113, formula: "C₂H₆O₂" },
  { name: "Propylene Glycol", category: "Solvent", density: 1036, viscosity: 58.1, conductivity: false,
    specificGravity: 1.036, formula: "C₃H₈O₂" },
  { name: "Glycerine (Glycerol)", category: "Solvent", density: 1261, viscosity: 1410, conductivity: false,
    specificGravity: 1.261, formula: "C₃H₈O₃", notes: "Very high viscosity" },
  { name: "MEK (Methyl Ethyl Ketone)", category: "Solvent", density: 805, viscosity: 0.43, conductivity: false,
    specificGravity: 0.805, formula: "C₄H₈O" },
  { name: "Toluene", category: "Solvent", density: 867, viscosity: 0.59, conductivity: false,
    specificGravity: 0.867, formula: "C₇H₈" },
  { name: "Benzene", category: "Solvent", density: 879, viscosity: 0.65, conductivity: false,
    specificGravity: 0.879, formula: "C₆H₆" },
  { name: "Xylene", category: "Solvent", density: 860, viscosity: 0.81, conductivity: false,
    specificGravity: 0.86, formula: "C₈H₁₀" },
  { name: "THF (Tetrahydrofuran)", category: "Solvent", density: 889, viscosity: 0.48, conductivity: false,
    specificGravity: 0.889, formula: "C₄H₈O" },
  { name: "DMF (Dimethylformamide)", category: "Solvent", density: 944, viscosity: 0.92, conductivity: false,
    specificGravity: 0.944, formula: "C₃H₇NO" },
  { name: "DMSO", category: "Solvent", density: 1100, viscosity: 1.99, conductivity: false,
    specificGravity: 1.1, formula: "C₂H₆OS" },

  // === OILS (18) ===
  { name: "Diesel", category: "Oil", density: 835, viscosity: 2.5, conductivity: false,
    specificGravity: 0.835, formula: "C₁₂H₂₃" },
  { name: "Light Diesel Oil (LDO)", category: "Oil", density: 860, viscosity: 4.0,
    specificGravity: 0.86, conductivity: false },
  { name: "Heavy Fuel Oil (HFO)", category: "Oil", density: 980, viscosity: 200, conductivity: false,
    specificGravity: 0.98, notes: "Bunker C" },
  { name: "Furnace Oil", category: "Oil", density: 950, viscosity: 80,
    specificGravity: 0.95, conductivity: false },
  { name: "Lube Oil (Light)", category: "Oil", density: 860, viscosity: 45,
    specificGravity: 0.86, conductivity: false },
  { name: "Lube Oil (Medium)", category: "Oil", density: 880, viscosity: 120,
    specificGravity: 0.88, conductivity: false },
  { name: "Lube Oil (Heavy)", category: "Oil", density: 900, viscosity: 350,
    specificGravity: 0.9, conductivity: false },
  { name: "Hydraulic Oil (ISO 32)", category: "Oil", density: 857, viscosity: 32,
    specificGravity: 0.857, conductivity: false },
  { name: "Hydraulic Oil (ISO 46)", category: "Oil", density: 868, viscosity: 46,
    specificGravity: 0.868, conductivity: false },
  { name: "Hydraulic Oil (ISO 68)", category: "Oil", density: 882, viscosity: 68,
    specificGravity: 0.882, conductivity: false },
  { name: "Transformer Oil", category: "Oil", density: 880, viscosity: 12, conductivity: false,
    specificGravity: 0.88, notes: "Insulating oil" },
  { name: "Turbine Oil", category: "Oil", density: 870, viscosity: 32,
    specificGravity: 0.87, conductivity: false },
  { name: "Cutting Oil (Soluble)", category: "Oil", density: 950, viscosity: 25,
    specificGravity: 0.95, conductivity: true },
  { name: "Cutting Oil (Neat)", category: "Oil", density: 820, viscosity: 15,
    specificGravity: 0.82, conductivity: false },
  { name: "Mineral Oil", category: "Oil", density: 850, viscosity: 20,
    specificGravity: 0.85, conductivity: false },
  { name: "Silicone Oil", category: "Oil", density: 960, viscosity: 100, conductivity: false,
    specificGravity: 0.96, formula: "(CH₃)₃SiO" },
  { name: "Palm Oil", category: "Oil", density: 915, viscosity: 45,
    specificGravity: 0.915, conductivity: false },
  { name: "Castor Oil", category: "Oil", density: 961, viscosity: 986,
    specificGravity: 0.961, conductivity: false },
  // === FUELS (8) ===
  { name: "Petrol / Gasoline", category: "Fuel", density: 720, viscosity: 0.5,
    specificGravity: 0.72, conductivity: false },
  { name: "Kerosene", category: "Fuel", density: 780, viscosity: 1.4,
    specificGravity: 0.78, conductivity: false },
  { name: "Aviation Turbine Fuel (ATF)", category: "Fuel", density: 780, viscosity: 1.2,
    specificGravity: 0.78, conductivity: false },
  { name: "LPG (Liquid)", category: "Fuel", density: 510, viscosity: 0.15, conductivity: false,
    specificGravity: 0.51, notes: "Liquid state at pressure" },
  { name: "Naphtha", category: "Fuel", density: 680, viscosity: 0.5,
    specificGravity: 0.68, conductivity: false },
  { name: "Biodiesel", category: "Fuel", density: 880, viscosity: 4.5,
    specificGravity: 0.88, conductivity: false },
  { name: "Ethanol Fuel (E85)", category: "Fuel", density: 770, viscosity: 1.1,
    specificGravity: 0.77, conductivity: false },
  { name: "Methanol Fuel", category: "Fuel", density: 792, viscosity: 0.59,
    specificGravity: 0.792, conductivity: false },
  // === CHEMICALS (15) ===
  { name: "Sodium Chloride (Brine 26%)", category: "Chemical", density: 1198, viscosity: 2.2, conductivity: true,
    specificGravity: 1.198, concentration: true, formula: "NaCl" },
  { name: "Calcium Chloride (Brine 30%)", category: "Chemical", density: 1280, viscosity: 3.5, conductivity: true,
    specificGravity: 1.28, concentration: true, formula: "CaCl₂" },
  { name: "Urea Solution (50%)", category: "Chemical", density: 1185, viscosity: 2.8, conductivity: true,
    specificGravity: 1.185, concentration: true, formula: "CO(NH₂)₂" },
  { name: "Hydrogen Peroxide (30%)", category: "Chemical", density: 1112, viscosity: 1.25, conductivity: true,
    specificGravity: 1.112, concentration: true, formula: "H₂O₂" },
  { name: "Sodium Hypochlorite (15%)", category: "Chemical", density: 1125, viscosity: 2.0, conductivity: true,
    specificGravity: 1.125, concentration: true, formula: "NaOCl" },
  { name: "Ferric Chloride (40%)", category: "Chemical", density: 1420, viscosity: 8.0, conductivity: true,
    specificGravity: 1.42, concentration: true, formula: "FeCl₃" },
  { name: "Aluminum Sulfate (50%)", category: "Chemical", density: 1330, viscosity: 5.0, conductivity: true,
    specificGravity: 1.33, concentration: true, formula: "Al₂(SO₄)₃" },
  { name: "Caustic Soda (15%)", category: "Chemical", density: 1150, viscosity: 3.0, conductivity: true,
    specificGravity: 1.15, concentration: true, formula: "NaOH" },
  { name: "Formaldehyde (37%)", category: "Chemical", density: 1080, viscosity: 1.8, conductivity: false,
    specificGravity: 1.08, concentration: true, formula: "CH₂O" },
  { name: "Aniline", category: "Chemical", density: 1022, viscosity: 4.4, conductivity: false,
    specificGravity: 1.022, formula: "C₆H₅NH₂" },
  { name: "Carbon Tetrachloride", category: "Chemical", density: 1594, viscosity: 0.97, conductivity: false,
    specificGravity: 1.594, formula: "CCl₄" },
  { name: "Chloroform", category: "Chemical", density: 1489, viscosity: 0.58, conductivity: false,
    specificGravity: 1.489, formula: "CHCl₃" },
  { name: "Methylene Chloride", category: "Chemical", density: 1326, viscosity: 0.43, conductivity: false,
    specificGravity: 1.326, formula: "CH₂Cl₂" },
  { name: "Sulfur Dioxide (Liquid)", category: "Chemical", density: 1460, viscosity: 0.29, conductivity: false,
    specificGravity: 1.46, formula: "SO₂" },
  { name: "Liquid Ammonia (-33°C)", category: "Chemical", density: 682, viscosity: 0.25, conductivity: true,
    specificGravity: 0.682, formula: "NH₃", notes: "At -33°C, liquid state" },

  // === FOOD & BEVERAGE (15) ===
  { name: "Milk", category: "Food & Beverage", density: 1030, viscosity: 2.0,
    specificGravity: 1.03, conductivity: true },
  { name: "Cream", category: "Food & Beverage", density: 994, viscosity: 10.0,
    specificGravity: 0.994, conductivity: true },
  { name: "Skimmed Milk", category: "Food & Beverage", density: 1035, viscosity: 1.4,
    specificGravity: 1.035, conductivity: true },
  { name: "Butter (Melted)", category: "Food & Beverage", density: 911, viscosity: 45.0, conductivity: false,
    specificGravity: 0.911, notes: "Non-Newtonian at low temp" },
  { name: "Edible Oil (Refined)", category: "Food & Beverage", density: 920, viscosity: 65.0,
    specificGravity: 0.92, conductivity: false },
  { name: "Sunflower Oil", category: "Food & Beverage", density: 920, viscosity: 50.0,
    specificGravity: 0.92, conductivity: false },
  { name: "Olive Oil", category: "Food & Beverage", density: 918, viscosity: 84.0,
    specificGravity: 0.918, conductivity: false },
  { name: "Coconut Oil", category: "Food & Beverage", density: 924, viscosity: 30.0,
    specificGravity: 0.924, conductivity: false },
  { name: "Palm Olein", category: "Food & Beverage", density: 918, viscosity: 35.0,
    specificGravity: 0.918, conductivity: false },
  { name: "Sugar Syrup (60%)", category: "Food & Beverage", density: 1289, viscosity: 56.0, conductivity: true,
    specificGravity: 1.289, concentration: true },
  { name: "Sugar Syrup (65%)", category: "Food & Beverage", density: 1331, viscosity: 110.0, conductivity: true,
    specificGravity: 1.331, concentration: true },
  { name: "Honey", category: "Food & Beverage", density: 1420, viscosity: 10000, conductivity: true,
    specificGravity: 1.42, nonNewtonian: true },
  { name: "Molasses", category: "Food & Beverage", density: 1400, viscosity: 5000, conductivity: true,
    specificGravity: 1.4, nonNewtonian: true },
  { name: "Corn Syrup", category: "Food & Beverage", density: 1330, viscosity: 1200, conductivity: true,
    specificGravity: 1.33, nonNewtonian: true },
  { name: "Tomato Ketchup", category: "Food & Beverage", density: 1130, viscosity: 50000, conductivity: true,
    specificGravity: 1.13, nonNewtonian: true },
  { name: "Juice (Orange)", category: "Food & Beverage", density: 1048, viscosity: 2.5,
    specificGravity: 1.048, conductivity: true },
  { name: "Beer", category: "Food & Beverage", density: 1008, viscosity: 1.4,
    specificGravity: 1.008, conductivity: true },
  { name: "Wine", category: "Food & Beverage", density: 990, viscosity: 1.8,
    specificGravity: 0.99, conductivity: true },
  { name: "Vinegar", category: "Food & Beverage", density: 1010, viscosity: 1.2,
    specificGravity: 1.01, conductivity: true },
  // === PHARMACEUTICAL (8) ===
  { name: "Liquid Paraffin", category: "Pharmaceutical", density: 850, viscosity: 110,
    specificGravity: 0.85, conductivity: false },
  { name: "Glycerin (USP)", category: "Pharmaceutical", density: 1261, viscosity: 1410, conductivity: false,
    specificGravity: 1.261, formula: "C₃H₈O₃" },
  { name: "Propylene Glycol (USP)", category: "Pharmaceutical", density: 1036, viscosity: 58.1,
    specificGravity: 1.036, conductivity: false },
  { name: "PEG 400", category: "Pharmaceutical", density: 1125, viscosity: 90, conductivity: false,
    specificGravity: 1.125, formula: "Polyethylene Glycol" },
  { name: "Ethanol (96%)", category: "Pharmaceutical", density: 805, viscosity: 1.4,
    specificGravity: 0.805, conductivity: false },
  { name: "Isopropyl Alcohol (IPA)", category: "Pharmaceutical", density: 786, viscosity: 2.4,
    specificGravity: 0.786, conductivity: false },
  { name: "Syrup (Simple)", category: "Pharmaceutical", density: 1330, viscosity: 85, conductivity: true,
    specificGravity: 1.33, nonNewtonian: true },
  { name: "Tincture", category: "Pharmaceutical", density: 850, viscosity: 1.5,
    specificGravity: 0.85, conductivity: false },
  // === SLURRIES (12) ===
  { name: "Cement Slurry", category: "Slurry", density: 1800, viscosity: 500, conductivity: false,
    specificGravity: 1.8, nonNewtonian: true, notes: "Abrasive" },
  { name: "Drilling Mud", category: "Slurry", density: 1200, viscosity: 50, conductivity: false,
    specificGravity: 1.2, nonNewtonian: true },
  { name: "Coal Slurry", category: "Slurry", density: 1300, viscosity: 200, conductivity: false,
    specificGravity: 1.3, nonNewtonian: true, notes: "Abrasive" },
  { name: "Sand Slurry", category: "Slurry", density: 1500, viscosity: 300, conductivity: false,
    specificGravity: 1.5, nonNewtonian: true, notes: "Highly abrasive" },
  { name: "Ash Slurry", category: "Slurry", density: 1200, viscosity: 100, conductivity: false,
    specificGravity: 1.2, nonNewtonian: true, notes: "Abrasive" },
  { name: "Lime Slurry", category: "Slurry", density: 1200, viscosity: 150, conductivity: true,
    specificGravity: 1.2, nonNewtonian: true },
  { name: "Kaolin Slurry", category: "Slurry", density: 1300, viscosity: 250, conductivity: false,
    specificGravity: 1.3, nonNewtonian: true },
  { name: "Bauxite Slurry", category: "Slurry", density: 1400, viscosity: 80, conductivity: false,
    specificGravity: 1.4, nonNewtonian: true, notes: "Abrasive" },
  { name: "Paper Pulp (4%)", category: "Slurry", density: 1020, viscosity: 20, conductivity: true,
    specificGravity: 1.02, nonNewtonian: true },
  { name: "Paper Pulp (6%)", category: "Slurry", density: 1035, viscosity: 80, conductivity: true,
    specificGravity: 1.035, nonNewtonian: true },
  { name: "Sewage Sludge", category: "Slurry", density: 1020, viscosity: 150, conductivity: true,
    specificGravity: 1.02, nonNewtonian: true },
  { name: "Mine Tailings", category: "Slurry", density: 1400, viscosity: 300, conductivity: false,
    specificGravity: 1.4, nonNewtonian: true, notes: "Abrasive" },

  // === GASES (Liquid State) (5) ===
  { name: "Liquid CO₂", category: "Gas (Liquid state)", density: 1032, viscosity: 0.07, conductivity: false,
    specificGravity: 1.032, formula: "CO₂", notes: "At -20°C, 19 bar" },
  { name: "Liquid Nitrogen", category: "Cryogenic", density: 808, viscosity: 0.16, conductivity: false,
    specificGravity: 0.808, formula: "N₂", notes: "At -196°C" },
  { name: "Liquid Oxygen", category: "Cryogenic", density: 1141, viscosity: 0.20, conductivity: false,
    specificGravity: 1.141, formula: "O₂", notes: "At -183°C" },
  { name: "Liquid Argon", category: "Cryogenic", density: 1394, viscosity: 0.25, conductivity: false,
    specificGravity: 1.394, formula: "Ar", notes: "At -186°C" },
  { name: "Liquid Natural Gas (LNG)", category: "Cryogenic", density: 422, viscosity: 0.14, conductivity: false,
    specificGravity: 0.422, notes: "At -162°C" },
  { name: "Liquid Petroleum Gas (LPG)", category: "Gas (Liquid state)", density: 510, viscosity: 0.15, conductivity: false,
    specificGravity: 0.51, notes: "At pressure, ~20°C" },

  // === CRYOGENIC ===
  { name: "Liquid Helium", category: "Cryogenic", density: 125, viscosity: 0.003, conductivity: false,
    specificGravity: 0.125, formula: "He", notes: "At -269°C" },
  { name: "Liquid Hydrogen", category: "Cryogenic", density: 71, viscosity: 0.014, conductivity: false,
    specificGravity: 0.071, formula: "H₂", notes: "At -253°C" },

  // === EXPANDED: ADDITIONAL VEGETABLE OILS ===
  { name: "Corn Oil", category: "Food & Beverage", density: 922, viscosity: 28,
    specificGravity: 0.922, conductivity: false },
  { name: "Soya Bean Oil", category: "Food & Beverage", density: 925, viscosity: 60,
    specificGravity: 0.925, conductivity: false },
  { name: "Rapeseed Oil (Canola)", category: "Food & Beverage", density: 915, viscosity: 65,
    specificGravity: 0.915, conductivity: false },
  { name: "Peanut Oil (Groundnut)", category: "Food & Beverage", density: 920, viscosity: 40,
    specificGravity: 0.92, conductivity: false },
  { name: "Cotton Seed Oil", category: "Food & Beverage", density: 926, viscosity: 62,
    specificGravity: 0.926, conductivity: false },
  { name: "Sesame Oil", category: "Food & Beverage", density: 920, viscosity: 55,
    specificGravity: 0.92, conductivity: false },
  { name: "Mustard Oil", category: "Food & Beverage", density: 914, viscosity: 58,
    specificGravity: 0.914, conductivity: false },
  { name: "Rice Bran Oil", category: "Food & Beverage", density: 916, viscosity: 45,
    specificGravity: 0.916, conductivity: false },
  // === EXPANDED: ADDITIONAL GLYCOLS & POLYOLS ===
  { name: "Diethylene Glycol", category: "Chemical", density: 1118, viscosity: 32, conductivity: false,
    specificGravity: 1.118, formula: "C₄H₁₀O₃" },
  { name: "Triethylene Glycol", category: "Chemical", density: 1125, viscosity: 40, conductivity: false,
    specificGravity: 1.125, formula: "C₆H₁₄O₄" },
  { name: "Dipropylene Glycol", category: "Chemical", density: 1023, viscosity: 85, conductivity: false,
    specificGravity: 1.023, formula: "C₆H₁₄O₃" },
  { name: "Tripropylene Glycol", category: "Chemical", density: 1022, viscosity: 65, conductivity: false,
    specificGravity: 1.022, formula: "C₉H₂₀O₄" },
  { name: "Hexylene Glycol", category: "Chemical", density: 924, viscosity: 29, conductivity: false,
    specificGravity: 0.924, formula: "C₆H₁₄O₂" },
  { name: "Polyol (PU A-Component)", category: "Chemical", density: 1100, viscosity: 85000, conductivity: false,
    specificGravity: 1.1, notes: " polyurethane component" },

  // === EXPANDED: ADDITIONAL INDUSTRIAL SOLVENTS ===
  { name: "Cyclohexane", category: "Solvent", density: 779, viscosity: 1.0, conductivity: false,
    specificGravity: 0.779, formula: "C₆H₁₂" },
  { name: "Carbon Disulfide", category: "Solvent", density: 1266, viscosity: 0.36, conductivity: false,
    specificGravity: 1.266, formula: "CS₂", notes: "Highly flammable" },
  { name: "Diethyl Ether", category: "Solvent", density: 714, viscosity: 0.22, conductivity: false,
    specificGravity: 0.714, formula: "(C₂H₅)₂O", notes: "Extremely flammable" },
  { name: "Pyridine", category: "Solvent", density: 983, viscosity: 0.95, conductivity: false,
    specificGravity: 0.983, formula: "C₅H₅N" },
  { name: "Acetonitrile", category: "Solvent", density: 786, viscosity: 0.34, conductivity: false,
    specificGravity: 0.786, formula: "CH₃CN" },
  { name: "Chlorobenzene", category: "Solvent", density: 1106, viscosity: 0.80, conductivity: false,
    specificGravity: 1.106, formula: "C₆H₅Cl" },
  { name: "N-Methylpyrrolidone (NMP)", category: "Solvent", density: 1030, viscosity: 1.7, conductivity: false,
    specificGravity: 1.03, formula: "C₅H₉NO" },
  { name: "Diethyl Ether", category: "Solvent", density: 714, viscosity: 0.24, conductivity: false,
    specificGravity: 0.714, formula: "(C₂H₅)₂O", notes: "Extremely flammable" },
  { name: "Iso-Octane", category: "Solvent", density: 692, viscosity: 0.50, conductivity: false,
    specificGravity: 0.692, formula: "C₈H₁₈" },
  { name: "Pentane", category: "Solvent", density: 626, viscosity: 0.22, conductivity: false,
    specificGravity: 0.626, formula: "C₅H₁₂" },
  { name: "Hexane", category: "Solvent", density: 659, viscosity: 0.31, conductivity: false,
    specificGravity: 0.659, formula: "C₆H₁₄" },
  { name: "Heptane", category: "Solvent", density: 684, viscosity: 0.39, conductivity: false,
    specificGravity: 0.684, formula: "C₇H₁₆" },
  { name: "Turpentine", category: "Solvent", density: 868, viscosity: 1.5, conductivity: false,
    specificGravity: 0.868, notes: "Natural pine solvent" },

  // === EXPANDED: ADDITIONAL ACIDS & ALKALIS ===
  { name: "Oxalic Acid (10%)", category: "Acid", density: 1015, viscosity: 1.1, conductivity: true,
    specificGravity: 1.015, concentration: true, formula: "C₂H₂O₄" },
  { name: "Tartaric Acid (20%)", category: "Acid", density: 1080, viscosity: 1.8, conductivity: true,
    specificGravity: 1.08, concentration: true, formula: "C₄H₆O₆" },
  { name: "Oleic Acid", category: "Acid", density: 894, viscosity: 36, conductivity: false,
    specificGravity: 0.894, formula: "C₁₈H₃₄O₂" },
  { name: "Stearic Acid (Melted)", category: "Acid", density: 847, viscosity: 12, conductivity: false,
    specificGravity: 0.847, formula: "C₁₈H₃₆O₂" },
  { name: "Phenol (Carbolic Acid)", category: "Acid", density: 1071, viscosity: 8.0, conductivity: false,
    specificGravity: 1.071, formula: "C₆H₅OH", notes: "Toxic, corrosive" },
  { name: "Cresol", category: "Acid", density: 1038, viscosity: 7.5, conductivity: false,
    specificGravity: 1.038, formula: "C₇H₈O", notes: "Toxic" },
  { name: "Caustic Potash (50%)", category: "Alkali", density: 1510, viscosity: 50, conductivity: true,
    specificGravity: 1.51, concentration: true, formula: "KOH" },
  { name: "Magnesium Hydroxide Slurry", category: "Alkali", density: 1100, viscosity: 80, conductivity: true,
    specificGravity: 1.1, nonNewtonian: true, formula: "Mg(OH)₂" },
  { name: "Aluminum Hydroxide Slurry", category: "Alkali", density: 1200, viscosity: 120, conductivity: true,
    specificGravity: 1.2, nonNewtonian: true },

  // === EXPANDED: ADDITIONAL OILS & LUBRICANTS ===
  { name: "Motor Oil (SAE 10)", category: "Oil", density: 880, viscosity: 85,
    specificGravity: 0.88, conductivity: false },
  { name: "Motor Oil (SAE 20)", category: "Oil", density: 885, viscosity: 180,
    specificGravity: 0.885, conductivity: false },
  { name: "Motor Oil (SAE 30)", category: "Oil", density: 890, viscosity: 300,
    specificGravity: 0.89, conductivity: false },
  { name: "Motor Oil (SAE 40)", category: "Oil", density: 895, viscosity: 500,
    specificGravity: 0.895, conductivity: false },
  { name: "Motor Oil (SAE 50)", category: "Oil", density: 900, viscosity: 750,
    specificGravity: 0.9, conductivity: false },
  { name: "Gear Oil (ISO 68)", category: "Oil", density: 900, viscosity: 68,
    specificGravity: 0.9, conductivity: false },
  { name: "Gear Oil (ISO 150)", category: "Oil", density: 910, viscosity: 150,
    specificGravity: 0.91, conductivity: false },
  { name: "Gear Oil (ISO 220)", category: "Oil", density: 915, viscosity: 220,
    specificGravity: 0.915, conductivity: false },
  { name: "Turbine Oil (ISO 32)", category: "Oil", density: 862, viscosity: 32,
    specificGravity: 0.862, conductivity: false },
  { name: "Turbine Oil (ISO 46)", category: "Oil", density: 868, viscosity: 46,
    specificGravity: 0.868, conductivity: false },
  { name: "Turbine Oil (ISO 68)", category: "Oil", density: 871, viscosity: 68,
    specificGravity: 0.871, conductivity: false },
  { name: "Compressor Oil (ISO 46)", category: "Oil", density: 870, viscosity: 46,
    specificGravity: 0.87, conductivity: false },
  { name: "Compressor Oil (ISO 68)", category: "Oil", density: 875, viscosity: 68,
    specificGravity: 0.875, conductivity: false },
  { name: "Way Oil (ISO 68)", category: "Oil", density: 880, viscosity: 68,
    specificGravity: 0.88, conductivity: false },
  { name: "Quench Oil", category: "Oil", density: 870, viscosity: 20, conductivity: false,
    specificGravity: 0.87, notes: "Heat treatment" },
  { name: "Refrigerant Oil", category: "Oil", density: 940, viscosity: 32, conductivity: false,
    specificGravity: 0.94, notes: "For HCFC systems" },
  { name: "Marine Diesel Oil", category: "Oil", density: 900, viscosity: 45,
    specificGravity: 0.9, conductivity: false },
  { name: "Marine Gas Oil", category: "Oil", density: 850, viscosity: 8,
    specificGravity: 0.85, conductivity: false },
  { name: "Biofuel (B100 Biodiesel)", category: "Fuel", density: 880, viscosity: 4.5,
    specificGravity: 0.88, conductivity: false },
  { name: "Fuel Oil (Light)", category: "Fuel", density: 860, viscosity: 5,
    specificGravity: 0.86, conductivity: false },
  { name: "Fuel Oil (Medium)", category: "Fuel", density: 920, viscosity: 40,
    specificGravity: 0.92, conductivity: false },
  { name: "Gasoil / DERV", category: "Fuel", density: 845, viscosity: 3,
    specificGravity: 0.845, conductivity: false },
  // === EXPANDED: ADDITIONAL FOOD & BEVERAGE ===
  { name: "Whey", category: "Food & Beverage", density: 1030, viscosity: 30,
    specificGravity: 1.03, conductivity: true },
  { name: "Yoghurt", category: "Food & Beverage", density: 1040, viscosity: 150, conductivity: true,
    specificGravity: 1.04, nonNewtonian: true },
  { name: "Mayonnaise", category: "Food & Beverage", density: 980, viscosity: 2000, conductivity: false,
    specificGravity: 0.98, nonNewtonian: true },
  { name: "Salad Cream", category: "Food & Beverage", density: 1020, viscosity: 2000, conductivity: false,
    specificGravity: 1.02, nonNewtonian: true },
  { name: "Treacle (70°Bx)", category: "Food & Beverage", density: 1350, viscosity: 400, conductivity: true,
    specificGravity: 1.35, nonNewtonian: true },
  { name: "Treacle (65°Bx)", category: "Food & Beverage", density: 1320, viscosity: 120, conductivity: true,
    specificGravity: 1.32, nonNewtonian: true },
  { name: "Liquid Egg", category: "Food & Beverage", density: 1030, viscosity: 150,
    specificGravity: 1.03, conductivity: true },
  { name: "Ice Cream Mix", category: "Food & Beverage", density: 1060, viscosity: 120, conductivity: true,
    specificGravity: 1.06, nonNewtonian: true },
  { name: "Soy Sauce", category: "Food & Beverage", density: 1180, viscosity: 25,
    specificGravity: 1.18, conductivity: true },
  { name: "Worcestershire Sauce", category: "Food & Beverage", density: 1080, viscosity: 18,
    specificGravity: 1.08, conductivity: true },
  { name: "Fruit Juice Concentrate", category: "Food & Beverage", density: 1120, viscosity: 80, conductivity: true,
    specificGravity: 1.12, concentration: true },

  // === EXPANDED: NON-NEWTONIAN / PASTES / EMULSIONS ===
  { name: "Toothpaste", category: "Pharmaceutical", density: 1350, viscosity: 70000, conductivity: true,
    specificGravity: 1.35, nonNewtonian: true },
  { name: "Shampoo", category: "Pharmaceutical", density: 1020, viscosity: 3000, conductivity: true,
    specificGravity: 1.02, nonNewtonian: true },
  { name: "Detergent (Liquid)", category: "Chemical", density: 1050, viscosity: 1200, conductivity: true,
    specificGravity: 1.05, nonNewtonian: true },
  { name: "Hand Cream", category: "Pharmaceutical", density: 980, viscosity: 800, conductivity: false,
    specificGravity: 0.98, nonNewtonian: true },
  { name: "Starch Solution (25°Bé)", category: "Chemical", density: 1040, viscosity: 300, conductivity: true,
    specificGravity: 1.04, nonNewtonian: true },
  { name: "Latex Emulsion", category: "Chemical", density: 1000, viscosity: 200, conductivity: false,
    specificGravity: 1.0, nonNewtonian: true },
  { name: "PVA Emulsion (White Glue)", category: "Chemical", density: 1050, viscosity: 8000, conductivity: false,
    specificGravity: 1.05, nonNewtonian: true },
  { name: "Printers Ink", category: "Chemical", density: 1100, viscosity: 1200, conductivity: false,
    specificGravity: 1.1, nonNewtonian: true },
  { name: "Bitumen (Cutback)", category: "Oil", density: 1000, viscosity: 500, conductivity: false,
    specificGravity: 1.0, nonNewtonian: true, notes: "Road construction" },

  // === EXPANDED: WATER TREATMENT & SPECIALTY ===
  { name: "Alum Solution (10%)", category: "Chemical", density: 1070, viscosity: 2.0, conductivity: true,
    specificGravity: 1.07, concentration: true, formula: "KAl(SO₄)₂" },
  { name: "Sodium Hypochlorite (5%)", category: "Chemical", density: 1060, viscosity: 1.5, conductivity: true,
    specificGravity: 1.06, concentration: true, formula: "NaOCl" },
  { name: "Polymer Flocculant Solution (0.5%)", category: "Chemical", density: 1000, viscosity: 50, conductivity: true,
    specificGravity: 1.0, nonNewtonian: true },
  { name: "Defoamer (Silicone Emulsion)", category: "Chemical", density: 980, viscosity: 350, conductivity: false,
    specificGravity: 0.98, nonNewtonian: true },
  { name: "Cooling Tower Blowdown", category: "Water", density: 1020, viscosity: 1.0,
    specificGravity: 1.02, conductivity: true },
  { name: "Reverse Osmosis Permeate", category: "Water", density: 998, viscosity: 1.0,
    specificGravity: 0.998, conductivity: false },
  { name: "Softened Water", category: "Water", density: 998, viscosity: 1.0,
    specificGravity: 0.998, conductivity: true },
  { name: "Grey Water (Treated)", category: "Water", density: 1000, viscosity: 1.1,
    specificGravity: 1.0, conductivity: true },
];

export function searchLiquids(query: string): LiquidData[] {
  if (!query || query.length < 1) return [];
  const q = query.toLowerCase();
  return LIQUIDS_DB.filter(
    (l) =>
      l.name.toLowerCase().includes(q) ||
      l.category.toLowerCase().includes(q) ||
      (l.formula && l.formula.toLowerCase().includes(q))
  ).slice(0, 10);
}

export function getLiquidsByCategory(category: string): LiquidData[] {
  return LIQUIDS_DB.filter((l) => l.category === category);
}
