// ============================================================
// Reflex Level Gauge Model Selector Data — 16 FlowRLG Models
// ============================================================

export interface RlgModelConfig {
  id: string;
  modelName: string;
  modelCode: string;
  configurablePositions: number[];
  allConfig: boolean;
  description: string;
  highlights: string[];
  datasheetFile?: string;
}

export const RLG_MODELS: RlgModelConfig[] = [
  { id: "l180", modelName: "FlowRLG L180", modelCode: "FMIPL-RLG-PC1-PCM1-PCS1-CC-NC-NP-RC1-RM1-D1-G1-SL1-ST1-NB", configurablePositions: [], allConfig: false, description: "Standard reflex level gauge. Flange-end, carbon steel body, reflex glass, SS 316 internals. For general liquid level measurement.", highlights: ["Connection: Flange ASA 150", "Body: Carbon Steel | Glass: Reflex", "Internals: SS 316 | Gasket: CAF", "Scale: Aluminium | Suitable: Water, Oil"], datasheetFile: "/datasheets/rlg/FlowRLG_L180__Reflex_Level_Gauge.pdf" },
  { id: "l180f", modelName: "FlowRLG L180F", modelCode: "FMIPL-RLG-PCM1-CC-NC-NP-RC1-RM1-D1-G1-SL1-ST1-NB", configurablePositions: [4,5,6], allConfig: false, description: "Reflex level gauge with variable connection type and standard. CS body, reflex glass, configurable connection options.", highlights: ["Variable: Connection type & standard", "Body: Carbon Steel | Glass: Reflex", "Internals: SS 316 | Gasket: CAF", "Scale: Aluminium | Suitable: Water, Oil"], datasheetFile: "/datasheets/rlg/FlowRLG_L180F__Reflex_Level_Gauge.pdf" },
  { id: "l180fv", modelName: "FlowRLG L180FV", modelCode: "FMIPL-RLG-PCM1-CC-NC-NP-RC1-RM1-D1-G1-SL1-ST1-NB", configurablePositions: [4,5,6,7,8], allConfig: false, description: "Fully variable reflex level gauge. CS body, configurable connection, standard, glass type, gasket, and scale.", highlights: ["Body: Carbon Steel | Fully configurable", "Glass: Reflex/Transparent | Gasket: CAF/PTFE", "Scale: Aluminium/SS 316", "Suitable: Water, Oil, Diesel"], datasheetFile: "/datasheets/rlg/FlowRLG_L180FV__Reflex_Level_Gauge.pdf" },
  { id: "l180v", modelName: "FlowRLG L180V", modelCode: "FMIPL-RLG-PC1-PCM1-PCS1-CC-NC-NP-RC1-RM1-D1-G1-SL1-ST1-NB", configurablePositions: [8,9], allConfig: false, description: "Reflex level gauge with variable glass and gasket. CS body, flange-end, reflex or transparent glass options.", highlights: ["Variable: Glass type & gasket", "Connection: Flange ASA 150", "Body: Carbon Steel | Glass: Reflex/Transparent", "Internals: SS 316 | Gasket: CAF/PTFE"], datasheetFile: "/datasheets/rlg/FlowRLG_L180V__Reflex_Level_Gauge.pdf" },
  { id: "l270", modelName: "FlowRLG L270", modelCode: "FMIPL-RLG-PC1-PCM2-PCS1-CC-NC-NP-RC1-RM1-D1-G1-SL1-ST1-NB", configurablePositions: [], allConfig: false, description: "Reflex level gauge with SS 316 body. Flange-end, reflex glass, SS 316 internals. For corrosive liquids.", highlights: ["Body: SS 316 | Glass: Reflex", "Connection: Flange ASA 150", "Internals: SS 316 | Gasket: CAF", "Scale: Aluminium | Suitable: Corrosive liquids"], datasheetFile: "/datasheets/rlg/FlowRLG_L270__Reflex_level_Gauge.pdf" },
  { id: "l270f", modelName: "FlowRLG L270F", modelCode: "FMIPL-RLG-PCM2-CC-NC-NP-RC1-RM1-D1-G1-SL1-ST1-NB", configurablePositions: [4,5,6,7,8,9], allConfig: false, description: "Reflex level gauge with SS 316 body and variable connections. Configurable connection type, standard, glass, gasket, scale, and reading type.", highlights: ["Body: SS 316 | Variable: All connections", "Glass: Reflex/Transparent | Gasket: CAF/PTFE/Graphoil", "Scale: Aluminium/SS 316 | Reading: Single/Dual", "Suitable: Corrosive liquids, Chemicals"], datasheetFile: "/datasheets/rlg/FlowRLG_L270F__Reflex_level_Gauge.pdf" },
  { id: "l270fv", modelName: "FlowRLG L270FV", modelCode: "FMIPL-RLG-PCM2-CC-NC-NP-RC1-RM1-D1-G1-SL1-ST1-NB", configurablePositions: [4,5,6,7,8,9,10], allConfig: false, description: "Fully variable reflex level gauge with SS 316 body. All components configurable for corrosive liquid applications.", highlights: ["Body: SS 316 | Fully configurable", "Glass: Reflex/Transparent | Gasket: CAF/PTFE/Graphoil", "Scale: Aluminium/SS 316 | Reading: Single/Dual", "Connection: Flange/Wafer/Threaded | Std: ASA 150/300"], datasheetFile: "/datasheets/rlg/FlowRLG_L270FV__Reflex_Level_Gauge.pdf" },
  { id: "l270v", modelName: "FlowRLG L270V", modelCode: "FMIPL-RLG-PC1-PCM2-PCS1-CC-NC-NP-RC1-RM1-D1-G1-SL1-ST1-NB", configurablePositions: [8,9], allConfig: false, description: "Reflex level gauge with SS 316 body and variable glass/gasket. Flange-end, reflex or transparent glass for corrosive liquids.", highlights: ["Body: SS 316 | Variable: Glass & gasket", "Connection: Flange ASA 150", "Glass: Reflex/Transparent | Gasket: CAF/PTFE", "Suitable: Corrosive liquids"], datasheetFile: "/datasheets/rlg/FlowRLG_L270V__Reflex_Level_Gauge.pdf" },
  { id: "l360", modelName: "FlowRLG L360", modelCode: "FMIPL-RLG-PC2-PCM3-PCS2-CC-NC-NP-RC1-RM1-D1-G1-SL1-ST1-NB", configurablePositions: [], allConfig: false, description: "Reflex level gauge for F&B applications. TC connection, SS 316 body and internals, ASME standard, reflex glass.", highlights: ["Connection: TC End | Std: ASME", "Body & Internals: SS 316", "Glass: Reflex | Gasket: CAF", "For Food & Beverage Industry"], datasheetFile: "/datasheets/rlg/FlowRLG_L360__Reflex_level_Gauge.pdf" },
  { id: "l360f", modelName: "FlowRLG L360F", modelCode: "FMIPL-RLG-PCM3-CC-NC-NP-RC1-RM1-D1-G1-SL1-ST1-NB", configurablePositions: [4,5,6,7,8,9,10], allConfig: false, description: "Reflex level gauge for F&B with variable connections. TC/Flange/Threaded options, SS 316 body, configurable all components.", highlights: ["Body: SS 316 | Variable: All connections", "Glass: Reflex/Transparent | Gasket: CAF/PTFE/Graphoil", "Scale: Aluminium/SS 316 | Reading: Single/Dual", "Connection: TC/Flange/Threaded | Std: ASME/ASA"], datasheetFile: "/datasheets/rlg/FlowRLG_L360F__Reflex_level_Gauge.pdf" },
  { id: "l360fv", modelName: "FlowRLG L360FV", modelCode: "FMIPL-RLG-PCM3-CC-NC-NP-RC1-RM1-D1-G1-SL1-ST1-NB", configurablePositions: [4,5,6,7,8,9,10,11], allConfig: false, description: "Fully variable reflex level gauge for F&B. SS 316 body, all components configurable including scale length and reading type.", highlights: ["Body: SS 316 | Fully configurable for F&B", "Glass: Reflex/Transparent | Gasket: CAF/PTFE/Graphoil", "Scale: Aluminium/SS 316 | Reading: Single/Dual", "Connection: TC/Flange/Threaded"], datasheetFile: "/datasheets/rlg/FlowRLG_L360FV__Reflex_Level_Gauge.pdf" },
  { id: "l360v", modelName: "FlowRLG L360V", modelCode: "FMIPL-RLG-PC2-PCM3-PCS2-CC-NC-NP-RC1-RM1-D1-G1-SL1-ST1-NB", configurablePositions: [8,9], allConfig: false, description: "Reflex level gauge for F&B with variable glass/gasket. TC connection, SS 316 body, reflex or transparent glass options.", highlights: ["Body: SS 316 | Variable: Glass & gasket", "Connection: TC End | Std: ASME", "Glass: Reflex/Transparent | Gasket: CAF/PTFE", "For Food & Beverage Industry"], datasheetFile: "/datasheets/rlg/FlowRLG_L360V__Reflex_Level_Gauge.pdf" },
  { id: "l450", modelName: "FlowRLG L450", modelCode: "FMIPL-RLG-PC1-PCM4-PCS1-CC-NC-NP-RC1-RM1-D1-G1-SL1-ST1-NB", configurablePositions: [], allConfig: false, description: "Reflex level gauge with PP body for highly corrosive applications. Flange-end, reflex glass, PP internals.", highlights: ["Body: Polypropylene (PP)", "Connection: Flange ASA 150", "Glass: Reflex | Gasket: CAF", "For highly corrosive liquids, Acids"], datasheetFile: "/datasheets/rlg/FlowRLG_L450__Reflex_level_Gauge.pdf" },
  { id: "l450f", modelName: "FlowRLG L450F", modelCode: "FMIPL-RLG-PCM4-CC-NC-NP-RC1-RM1-D1-G1-SL1-ST1-NB", configurablePositions: [4,5,6,7,8,9,10], allConfig: false, description: "Reflex level gauge with PP body and variable connections. Configurable connection type, standard, glass, gasket, scale, and reading type.", highlights: ["Body: Polypropylene (PP)", "Variable: Connection, std, glass, gasket, scale", "Glass: Reflex/Transparent | Gasket: CAF/PTFE/Graphoil", "For highly corrosive liquids"], datasheetFile: "/datasheets/rlg/FlowRLG_L450F__Reflex_level_Gauge.pdf" },
  { id: "l450fv", modelName: "FlowRLG L450FV", modelCode: "FMIPL-RLG-PCM4-CC-NC-NP-RC1-RM1-D1-G1-SL1-ST1-NB", configurablePositions: [4,5,6,7,8,9,10,11], allConfig: false, description: "Fully variable reflex level gauge with PP body. All components configurable for highly corrosive applications.", highlights: ["Body: Polypropylene (PP) | Fully configurable", "Glass: Reflex/Transparent | Gasket: CAF/PTFE/Graphoil", "Scale: Aluminium/SS 316 | Reading: Single/Dual", "Connection: Flange/Wafer/Threaded"], datasheetFile: "/datasheets/rlg/FlowRLG_L450FV__Reflex_Level_Gauge.pdf" },
  { id: "l450v", modelName: "FlowRLG L450V", modelCode: "FMIPL-RLG-PC1-PCM4-PCS1-CC-NC-NP-RC1-RM1-D1-G1-SL1-ST1-NB", configurablePositions: [8,9], allConfig: false, description: "Reflex level gauge with PP body and variable glass/gasket. Flange-end, reflex or transparent glass for highly corrosive liquids.", highlights: ["Body: Polypropylene (PP)", "Variable: Glass type & gasket", "Connection: Flange ASA 150", "For highly corrosive liquids, Acids"], datasheetFile: "/datasheets/rlg/FlowRLG_L450V__Reflex_Level_Gauge.pdf" },
];

export const RLG_MODEL_MAP: Record<string, RlgModelConfig> = Object.fromEntries(
  RLG_MODELS.map((m) => [m.id, m])
);
