// ============================================================
// Tubular Level Indicator Model Selector Data — 16 FlowTLI Models
// ============================================================

export interface TliModelConfig {
  id: string;
  modelName: string;
  modelCode: string;
  configurablePositions: number[];
  allConfig: boolean;
  description: string;
  highlights: string[];
  datasheetFile?: string;
}

export const TLI_MODELS: TliModelConfig[] = [
  { id: "l180", modelName: "FlowTLI L180", modelCode: "FMIPL-TLI-PC1-PCM1-PCS1-CC-NC-NP-RC1-RM1-D1-G1-SL1-ST1-NB", configurablePositions: [], allConfig: false, description: "Standard tubular level indicator. Flange-end connection, CS body, reflex glass, SS 316 internals. For general liquid level measurement.", highlights: ["Connection: Flange ASA 150", "Body: Carbon Steel | Glass: Reflex", "Internals: SS 316 | Gasket: CAF", "Scale: Aluminium | Suitable: Water, Oil"], datasheetFile: "/datasheets/tli/FlowTLI_L180__Tubular_Level_Indicator.pdf" },
  { id: "l180f", modelName: "FlowTLI L180F", modelCode: "FMIPL-TLI-PCM1-CC-NC-NP-RC1-RM1-D1-G1-SL1-ST1-NB", configurablePositions: [4,5,6], allConfig: false, description: "Tubular level indicator with variable connection type and standard. Flange/Wafer/Threaded options. CS body with reflex glass.", highlights: ["Variable: Connection type & standard", "Body: Carbon Steel | Glass: Reflex", "Internals: SS 316 | Gasket: CAF", "Scale: Aluminium | Suitable: Water, Oil"], datasheetFile: "/datasheets/tli/FlowTLI_L180F__Tubular_Level_Indicator.pdf" },
  { id: "l180fv", modelName: "FlowTLI L180FV", modelCode: "FMIPL-TLI-PCM1-CC-NC-NP-RC1-RM1-D1-G1-SL1-ST1-NB", configurablePositions: [4,5,6,7,8], allConfig: false, description: "Fully variable tubular level indicator. Configurable connection type, standard, glass type, gasket, and scale. CS body.", highlights: ["Variable: Connection, std, glass, gasket, scale", "Body: Carbon Steel | Glass: Reflex/Transparent", "Internals: SS 316", "Max C-C: 3000mm | Suitable: Water, Oil"], datasheetFile: "/datasheets/tli/FlowTLI_L180FV__Tubular_Level_Indicator.pdf" },
  { id: "l180v", modelName: "FlowTLI L180V", modelCode: "FMIPL-TLI-PC1-PCM1-PCS1-CC-NC-NP-RC1-RM1-D1-G1-SL1-ST1-NB", configurablePositions: [8,9], allConfig: false, description: "Tubular level indicator with variable glass and gasket options. Reflex or transparent glass with CAF or PTFE gasket.", highlights: ["Variable: Glass type & gasket", "Connection: Flange ASA 150", "Body: Carbon Steel | Glass: Reflex/Transparent", "Internals: SS 316 | Gasket: CAF/PTFE"], datasheetFile: "/datasheets/tli/FlowTLI_L180V__Tubular_Level_Indicator.pdf" },
  { id: "l270", modelName: "FlowTLI L270", modelCode: "FMIPL-TLI-PC1-PCM2-PCS1-CC-NC-NP-RC1-RM1-D1-G1-SL1-ST1-NB", configurablePositions: [], allConfig: false, description: "Tubular level indicator with SS 316 body. Flange-end connection, reflex glass, SS 316 internals. For corrosive liquids.", highlights: ["Body: SS 316 | Glass: Reflex", "Connection: Flange ASA 150", "Internals: SS 316 | Gasket: CAF", "Suitable: Corrosive liquids, Chemicals"], datasheetFile: "/datasheets/tli/FlowTLI_L270__Tubular_Level_Indicator.pdf" },
  { id: "l270f", modelName: "FlowTLI L270F", modelCode: "FMIPL-TLI-PCM2-CC-NC-NP-RC1-RM1-D1-G1-SL1-ST1-NB", configurablePositions: [4,5,6,7,8,9,10], allConfig: false, description: "Tubular level indicator with SS 316 body and fully variable connections. Configurable connection type, standard, glass, gasket, scale, and scale type.", highlights: ["Body: SS 316 | Variable: All connections", "Glass: Reflex/Transparent | Gasket: CAF/PTFE", "Scale: Aluminium/SS 316 | Reading: Single/Dual", "Suitable: Corrosive liquids"], datasheetFile: "/datasheets/tli/FlowTLI_L270F__Tubular_Level_Indicator.pdf" },
  { id: "l270fv", modelName: "FlowTLI L270FV", modelCode: "FMIPL-TLI-PCM2-CC-NC-NP-RC1-RM1-D1-G1-SL1-ST1-NB", configurablePositions: [4,5,6,7,8,9,10,11], allConfig: false, description: "Fully variable tubular level indicator with SS 316 body. All components configurable including scale length, glass type, gasket, and reading type.", highlights: ["Body: SS 316 | Fully configurable", "Glass: Reflex/Transparent | Gasket: CAF/PTFE/Graphoil", "Scale: Aluminium/SS 316 | Reading: Single/Dual", "Max C-C: 3000mm | Suitable: Corrosive liquids"], datasheetFile: "/datasheets/tli/FlowTLI_L270FV__Tubular_Level_Indicator.pdf" },
  { id: "l270v", modelName: "FlowTLI L270V", modelCode: "FMIPL-TLI-PC1-PCM2-PCS1-CC-NC-NP-RC1-RM1-D1-G1-SL1-ST1-NB", configurablePositions: [8,9], allConfig: false, description: "Tubular level indicator with SS 316 body and variable glass/gasket. Reflex or transparent glass with CAF or PTFE gasket.", highlights: ["Body: SS 316 | Variable: Glass & gasket", "Connection: Flange ASA 150", "Glass: Reflex/Transparent | Gasket: CAF/PTFE", "Suitable: Corrosive liquids, Chemicals"], datasheetFile: "/datasheets/tli/FlowTLI_L270V__Tubular_Level_Indicator.pdf" },
  { id: "l360", modelName: "FlowTLI L360", modelCode: "FMIPL-TLI-PC2-PCM3-PCS2-CC-NC-NP-RC1-RM1-D1-G1-SL1-ST1-NB", configurablePositions: [], allConfig: false, description: "Tubular level indicator for F&B applications. TC connection, SS 316 body and internals, ASME standard, reflex glass.", highlights: ["Connection: TC End | Std: ASME", "Body & Internals: SS 316", "Glass: Reflex | Gasket: CAF", "For Food & Beverage Industry"], datasheetFile: "/datasheets/tli/FlowTLI_L360__Tubular_Level_Indicator.pdf" },
  { id: "l360f", modelName: "FlowTLI L360F", modelCode: "FMIPL-TLI-PCM3-CC-NC-NP-RC1-RM1-D1-G1-SL1-ST1-NB", configurablePositions: [4,5,6,7,8,9], allConfig: false, description: "Tubular level indicator for F&B with variable connections. TC/Flange/Threaded options, SS 316 body, configurable glass and gasket.", highlights: ["Body: SS 316 | Variable: Connection, std, glass, gasket", "Connection: TC/Flange/Threaded | Std: ASME/ASA", "Glass: Reflex/Transparent | Gasket: CAF/PTFE", "For Food & Beverage Industry"], datasheetFile: "/datasheets/tli/FlowTLI_L360F__Tubular_Level_Indicator.pdf" },
  { id: "l360fv", modelName: "FlowTLI L360FV", modelCode: "FMIPL-TLI-PCM3-CC-NC-NP-RC1-RM1-D1-G1-SL1-ST1-NB", configurablePositions: [4,5,6,7,8,9,10], allConfig: false, description: "Fully variable tubular level indicator for F&B. SS 316 body, all components configurable including scale type and reading.", highlights: ["Body: SS 316 | Fully configurable for F&B", "Glass: Reflex/Transparent | Gasket: CAF/PTFE/Graphoil", "Scale: Aluminium/SS 316 | Reading: Single/Dual", "Connection: TC/Flange/Threaded"], datasheetFile: "/datasheets/tli/FlowTLI_L360FV__Tubular_Level_Indicator.pdf" },
  { id: "l360v", modelName: "FlowTLI L360V", modelCode: "FMIPL-TLI-PC2-PCM3-PCS2-CC-NC-NP-RC1-RM1-D1-G1-SL1-ST1-NB", configurablePositions: [8,9], allConfig: false, description: "Tubular level indicator for F&B with variable glass/gasket. TC connection, SS 316 body, reflex or transparent glass.", highlights: ["Body: SS 316 | Variable: Glass & gasket", "Connection: TC End | Std: ASME", "Glass: Reflex/Transparent | Gasket: CAF/PTFE", "For Food & Beverage Industry"], datasheetFile: "/datasheets/tli/FlowTLI_L360V__Tubular_Level_Indicator.pdf" },
  { id: "l450", modelName: "FlowTLI L450", modelCode: "FMIPL-TLI-PC1-PCM4-PCS1-CC-NC-NP-RC1-RM1-D1-G1-SL1-ST1-NB", configurablePositions: [], allConfig: false, description: "Tubular level indicator with PP body for highly corrosive applications. Flange-end, reflex glass, PP internals.", highlights: ["Body: Polypropylene (PP)", "Connection: Flange ASA 150", "Glass: Reflex | Gasket: CAF", "For highly corrosive liquids"], datasheetFile: "/datasheets/tli/FlowTLI_L450__Tubular_Level_Indicator.pdf" },
  { id: "l450f", modelName: "FlowTLI L450F", modelCode: "FMIPL-TLI-PCM4-CC-NC-NP-RC1-RM1-D1-G1-SL1-ST1-NB", configurablePositions: [4,5,6,7,8,9,10,11], allConfig: false, description: "Tubular level indicator with PP body and variable connections. Configurable connection type, standard, glass, gasket, scale, and scale type.", highlights: ["Body: Polypropylene (PP)", "Variable: Connection, std, glass, gasket, scale", "Glass: Reflex/Transparent | Gasket: CAF/PTFE/Graphoil", "For highly corrosive liquids"], datasheetFile: "/datasheets/tli/FlowTLI_L450F__Tubular_Level_Indicator.pdf" },
  { id: "l450fv", modelName: "FlowTLI L450FV", modelCode: "FMIPL-TLI-PCM4-CC-NC-NP-RC1-RM1-D1-G1-SL1-ST1-NB", configurablePositions: [4,5,6,7,8,9,10,11,12], allConfig: false, description: "Fully variable tubular level indicator with PP body. All components configurable for highly corrosive applications.", highlights: ["Body: Polypropylene (PP) | Fully configurable", "Glass: Reflex/Transparent | Gasket: CAF/PTFE/Graphoil", "Scale: Aluminium/SS 316 | Reading: Single/Dual", "Connection: Flange/Wafer/Threaded"], datasheetFile: "/datasheets/tli/FlowTLI_L450FV__Tubular_Level_Indicator.pdf" },
  { id: "l450v", modelName: "FlowTLI L450V", modelCode: "FMIPL-TLI-PC1-PCM4-PCS1-CC-NC-NP-RC1-RM1-D1-G1-SL1-ST1-NB", configurablePositions: [8,9], allConfig: false, description: "Tubular level indicator with PP body and variable glass/gasket. Reflex or transparent glass for highly corrosive liquids.", highlights: ["Body: Polypropylene (PP)", "Variable: Glass type & gasket", "Connection: Flange ASA 150", "For highly corrosive liquids, Acids"], datasheetFile: "/datasheets/tli/FlowTLI_L450V__Tubular_Level_Indicator.pdf" },
];

export const TLI_MODEL_MAP: Record<string, TliModelConfig> = Object.fromEntries(
  TLI_MODELS.map((m) => [m.id, m])
);
